

[[selection]]
== Selection of date and time

[[selection-general]]
=== General

A time scale component can be replaced with selection rules to specify
matching criteria of certain time scale unit values. This clause builds
upon the "`explicit`" syntax of time scale components specified in
<<CC18011>>.

[selection] may include zero or more selection rules.

[source]
----
selection = [selection-rule-1]...[selection-rule-n]
----

Generally, selection rules should be placed in the order where the
higher-order time scale components are placed on the left, and the
lower-order ones placed on the right.

While it is possible to translate the selection rules specified in this
document to the "`RECUR`" syntax specified in <<RFC5545>> in most cases;
exceptions and limitations are noted within context of the rules
specified below.


[[selection-months]]
=== Selection of calendar months

This selection rule specifies a set of calendar months of the calendar year.

Representation:

[source]
----
monthSR = [monthE]
----

Valid values are [1] to [12], corresponding to the ordinal number of the calendar month.

[example]
`3M` represents the third calendar month of the calendar year, i.e. March.



[[selection-weeks]]
=== Selection of calendar weeks

This selection rule specifies a set of ordinals specifying calendar weeks of the calendar year.

Representation:

[source]
----
weekSR = [weekE]
----

Valid values are [1] to [53] and [-53] to [-1]. This corresponds to the
number of calendar weeks of a year according to week numbering as
defined in <<ISO8601-1>>.

This rule should only be specified when the frequency of the repeat
rule is set to yearly (<<eligible-time-intervals-year>>).

[example]
The third week of the calendar year is represented by the expression
`3W` in this part.

NOTE: Week 53 can only occur when Thursday is January 1 or if it is a
leap calendar year and Wednesday is January 1, in accordance with
<<ISO8601-1,clause 4.2.2>>.

NOTE: Refer to <<CC18011,clause 6.7>> for negative values of weeks.

NOTE: Definitions of the calendar week and the week number are provided
in <<ISO8601-1>>.


[[selection-month-days]]
=== Selection of calendar month days

This selection rule specifies a set of days of the calendar month.

Representation:

[source]
----
daySR = [dayE]
----

Valid values are [1] to [31] and [-31] to [-1]. This corresponds to the
maximum number of calendar days of a calendar month.

[example]
`-10D` represents the tenth to the last calendar day of the calendar
month.

When the frequency part is set to weekly
(<<eligible-time-intervals-week>>), this selection rule must not be
specified.


[[selection-week-days]]
=== Selection of week days
This selection rule specifies a set of days of the week.

Representation:

[source]
----
daykSR = [daykE]
----

Valid values are [1] to [7].

[example]
Within a monthly rule, "`1K`" represents all Mondays within the calendar
month.


[[selection-weeks-position]]
=== Selection of calendar week days with position

This selection rule indicates the n-th occurrence of a specific week
day within a yearly (<<eligible-time-intervals-year>>) or monthly
(<<eligible-time-intervals-month>>) intervals.

Representation:

[source]
----
daykR = [!]["`-`"][i]["`J`"][daykE]
----

This representation should be used only with repeating rules with
intervals of a higher order time scale unit than "`week`", such as
"`yearly`" or "`monthly`". Valid values of [i] range from [1] to [53] and
[-53] to [-1].

The numeric value [i] in this rule corresponds to an offset within a
given scope:

* when the frequency is yearly, and when there is a rule for selection
of calendar month, then the offset corresponds to an offset within the
calendar month specified in the selection of month rule;

* when there is a rule for selection of week or for selection of
calendar month, then the offset corresponds to an offset within the
calendar year.


[example]
When specified in a monthly context, `+1j1K` represents the first
Monday within the calendar month, whereas `{1,-2}j1K` represents the
first and the second last Monday of the calendar month.


[example]
When specified in a yearly context, `+52j1K` represents the 52th Monday
within the calendar year, whereas `-21j1K` represents the 21st Monday
counted from the last week of the calendar year.


[[selection-ordinal-days]]
=== Selection of ordinal days in calendar year

This selection rule specifies a set of ordinal days of the calendar
year, and should only be specified when the interval of the repeat rule
is set to yearly (<<eligible-time-intervals-year>>), monthly
(<<eligible-time-intervals-month>>) or daily
(<<eligible-time-intervals-day>>).

Representation:

[source]
----
dayoSR = [dayoE(m)]
----

Valid values are [1] to [366] and [–366] to [-1].

NOTE: The values of [366] and [-366] are used to match a calendar leap year

[example]
`-1` represents the last day of the calendar year (December 31st)

[example]
`-306` represents the 306th to the last day of the calendar year (March 1st)


[[selection-hours]]
=== Selection of hours

This selection rule specifies a set of hours of the calendar day.

Representation:

[source]
----
hourSR = [hourE]
----

Valid values are [0] to [23].


[[selection-minutes]]
=== Selection of minutes

This selection rule specifies a set of minutes within an hour.

Representation:

[source]
----
minSR = [minE]
----

Valid values are [0] to [59].


[[selection-seconds]]
=== Selection of seconds

This selection rule specifies a set of seconds within a minute.

Representation:

[source]
----
secSR = [secE]
----

Valid values are [0] to [60].

NOTE: The value of [60] is used to match a leap second of the calendar year.

NOTE: The value of [60] should be changed to [59] when converting such
rule that to the <<RFC5545>> `BYSECOND` since the `BYSECOND` syntax
does not support a value of [60].


[[selection-position]]
=== Selection of position

The positional part is an optional part in a selection rule.

It specifies a set of values that corresponds to the n-th occurrence
within selected occurrences.
Particularly, it operates on a set of recurrence instances in one
interval of the repeating rule.

A set of recurrence instances starts at the beginning of the interval
defined by the frequency part.

The selection of position should only be used when there is at least
one selection rule is specified.

Representation:

[source]
----
positionSR = [position]["`I`"]
----

Where,

[source]
----
position = [!]["`-`"][i]
----

Each [position] value can include a positive (+n) or negative (-n)
integer. Valid values for [position] are therefore unbounded,
except for the integer value [0], which is not accepted.

Position numbers within a set of occurrences is considered to
start with [1] (the first occurence of the set of occurrences),
and [-1] represents the first occurence when counted backwards.


[example]
In a repeating rule with a weekly frequency, the interval would be one
week.

[example]
"`The last work day of calendar months`" can be represented by the
repeating rule `F1ML{1,2,3,4,5}K-1I` (using notation specified in
<<integer-ops>>)

