:repo-name: csd-general-recurrence

= CalConnect Standard: Date and time -- General recurrence representation

This work item belongs to TC DATETIME.

image:https://travis-ci.com/CalConnect/csd-general-recurrence.svg?branch=master["Build Status", link="https://travis-ci.com/CalConnect/csd-general-recurrence"]

This document is available in its rendered forms here:

* https://calconnect.github.io/csd-general-recurrence/[Date and time -- General recurrence representation (HTML)]
* https://calconnect.github.io/csd-general-recurrence/csd-general-recurrence.pdf[PDF]
* https://calconnect.github.io/csd-general-recurrence/csd-general-recurrence.xml[Metanorma XML]
* https://calconnect.github.io/csd-general-recurrence/csd-general-recurrence.rxl[Relaton XML (Bibliographic item)]

Because of all this, there is no need to build the document on your own, but if you wish to do so, this is how it can be done:

== Fetching the document

[source,sh]
----
git clone https://github.com/CalConnect/csd-general-recurrence/
----

== Installing Build Tools

See https://www.metanorma.com/overview/getting-started/


== Running via Docker or locally

If you have installed the build tools locally, and wish to run the
locally-installed compilation tools, there is nothing further to set.

If you don't want to deal with local dependencies, use the docker
version by:

[source,sh]
----
export METANORMA_DOCKER=1
----

The `Makefile` will automatically choose the proper command to
execute.


== Building The Document

[source,sh]
----
make clean all
----

The following outputs will be built:

* CSD XML (https://github.com/calconnect/metanorma-model-csd) (`[filename].xml`)
* HTML (`[filename].html`)
* PDF (`[filename].pdf`)
* Word DOC (`[filename].doc`)


== Iterating the document

[source,sh]
----
make html
open csd-*.html
----

